### ISSUE TITLE
Cannot get private repositories

### ISSUE THREAD

**Issue by devboxr** [KnpLabs/php-github-api#471] opened 2016-11-22 13:34 UTC
Created an oAuth application for our Organisation.

Trying to use this code:

```php
$client = new \Github\Client();
$client->authenticate($clientId, $secret, \Github\Client::AUTH_URL_CLIENT_ID);

print_r($repo = $client->api('current_user')->repositories());
```

Throws an `Requires authentication` exception.

I also tried:

```php
print_r($repo = $client->api('organization')->repositories('SamKnows')); // Only shows public ones
```

Any idea? It doesn't seem to authorise at all and the `authenticate` method returns `null`.

**Comment by devboxr** [comment] 2016-11-22 14:09
I tried a few things more, like retrieving an `access_token` with the `repo` scope, but this only gives me access to my personal repositories and the public ones of the organisation I'm trying to access.

Any help would be great.

**Comment by Nyholm** [comment] 2016-12-04 12:32
Have you seen #440 ?

**Comment by jdc1898** [comment] 2017-01-26 04:09
Were you ever able to get "print_r($repo = $client->api('organization')->repositories('SamKnows')); // Only shows public ones" to work? 
I am able to manipulate resources post auth on a private repo, but I can't list the private repo's linked to the authenticated user.

**Comment by AlexObreja** [comment] 2019-06-21 00:07
It was fixed this issue?

**Comment by GrahamCampbell** [comment] 2019-06-21 12:33
> It was fixed this issue?

There isn't a bug in this library? The issue is caused by the user not having the correct scopes on their access token. This issue should be closed tbh, or at least the bug label removed, because there is no bug.

**Comment by acrobat** [comment] 2019-06-23 20:04
Thanks @GrahamCampbell for jumping in on this issue. It does indeed seem to me that the access token had not the correct scopes to access private repositories.

So closing this issue as it's not a bug in the library.

**Closed by acrobat** 2019-06-23 20:04 UTC
Labels: bug
