### ISSUE TITLE
Bug on OptionsResolver php 7.2.8

### ISSUE THREAD

**Issue by oitsuki** [KnpLabs/php-github-api#727] opened 2018-08-18 13:02 UTC
PHP Parse error:  syntax error, unexpected '?', expecting variable (T_VARIABLE) in /var/..................................../vendor/symfony/options-resolver/OptionsResolver.php on line 980

**Comment by oitsuki** [comment] 2018-08-18 23:09
yes completly, I will look about the cli

**Comment by robbieaverill** [comment] 2018-09-06 10:11
Assuming you're using symfony/options-resolver v4.1.1, this is the method signature: https://github.com/symfony/options-resolver/blob/v4.1.1/OptionsResolver.php#L980

The question mark signifies a nullable scalar type hint, and was introduced in PHP 7.1.

@acrobat's suggestion that you're running something lower than PHP 7.1 in the environment where that error is generated is highly likely to be the cause of your problem. Either way, I don't think there's a problem with this library here.

**Comment by acrobat** [comment] 2018-09-12 10:36
I'm closing this issue as it will be related to the php installation instead of the library itself. Please leave a comment if it would be related to this library.

**Closed by acrobat** 2018-09-12 10:36 UTC
