### ISSUE TITLE
Could not add assignee to issue! Got: "Not Found"

### ISSUE THREAD

**Issue by OskarStark** [KnpLabs/php-github-api#828] opened 2019-11-04 07:57 UTC
Hi, I am using the following code:

```php
$issue = $this->github->issues()->create($org = 'gansel-rechtsanwaelte', $repo = 'lf', [
    'title' => 'test',
    'body' => 'test body',
]);
dump($issue); // the issue gets created!

$assignees = $this->github->api('issue')->assignees()->listAvailable($org, $repo);
dump($assignees); // all of them are listed

// try to assign myself to an issue (I am org and repo owner)
$this->github->api('issue')->assignees()->add($org, $repo, $issue['id'], [
    'assignees' => ['OskarStark']
]);
```

<details>
<summary>The error</summary>
In GithubExceptionThrower.php line 100:

  [Github\Exception\RuntimeException (404)]
  Not Found

Exception trace:
  at /app/vendor/knplabs/github-api/lib/Github/HttpClient/Plugin/GithubExceptionThrower.php:100
 Github\HttpClient\Plugin\GithubExceptionThrower->Github\HttpClient\Plugin\{closure}() at /app/vendor/php-http/httplug/src/Promise/HttpFulfilledPromise.php:34
 Http\Client\Promise\HttpFulfilledPromise->then() at /app/vendor/knplabs/github-api/lib/Github/HttpClient/Plugin/GithubExceptionThrower.php:101
 Github\HttpClient\Plugin\GithubExceptionThrower->doHandleRequest() at /app/vendor/php-http/client-common/src/Plugin/VersionBridgePlugin.php:22
 Github\HttpClient\Plugin\GithubExceptionThrower->handleRequest() at /app/vendor/php-http/client-common/src/PluginClient.php:132
 Http\Client\Common\PluginClient->Http\Client\Common\{closure}() at /app/vendor/php-http/client-common/src/PluginClient.php:146
 Http\Client\Common\PluginClient->Http\Client\Common\{closure}() at /app/vendor/php-http/client-common/src/PluginClient.php:90
 Http\Client\Common\PluginClient->sendRequest() at /app/vendor/php-http/client-common/src/HttpMethodsClient.php:82
 Http\Client\Common\HttpMethodsClient->sendRequest() at /app/vendor/php-http/client-common/src/HttpMethodsClient.php:73
 Http\Client\Common\HttpMethodsClient->send() at /app/vendor/php-http/client-common/src/HttpMethodsClient.php:47
 Http\Client\Common\HttpMethodsClient->post() at /app/vendor/knplabs/github-api/lib/Github/Api/AbstractApi.php:164
 Github\Api\AbstractApi->postRaw() at /app/vendor/knplabs/github-api/lib/Github/Api/AbstractApi.php:146
 Github\Api\AbstractApi->post() at /app/vendor/knplabs/github-api/lib/Github/Api/Issue/Assignees.php:66
 Github\Api\Issue\Assignees->add() at /app/src/Command/Test/TestRamicroCreateAkteCommand.php:79
 App\Command\Test\TestRamicroCreateAkteCommand->execute() at /app/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /app/vendor/symfony/console/Application.php:952
 Symfony\Component\Console\Application->doRunCommand() at /app/vendor/symfony/framework-bundle/Console/Application.php:87
 Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand() at /app/vendor/symfony/console/Application.php:273
 Symfony\Component\Console\Application->doRun() at /app/vendor/symfony/framework-bundle/Console/Application.php:73
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /app/vendor/symfony/console/Application.php:149
 Symfony\Component\Console\Application->run() at /app/bin/console:42
</details>

Checked the Github-API docs, but everything looks correct:
https://developer.github.com/v3/issues/assignees/#parameters

**Comment by GrahamCampbell** [comment] 2019-11-04 09:42
Does your API key have permission?

**Comment by OskarStark** [comment] 2019-11-04 12:41
Hi Graham,

these are my scopes.
![Screenshot 2019-11-04 13 40 55](https://user-images.githubusercontent.com/995707/68121739-cadfda00-ff08-11e9-9551-579a932bb261.png)

**Comment by GrahamCampbell** [comment] 2019-11-04 17:19
What happens if you give it all scopes?

**Comment by GrahamCampbell** [comment] 2019-11-04 17:20
I'm wondering if they are blocking it because the success implicitly leaks organisation membership information?

**Comment by OskarStark** [comment] 2019-11-04 17:31
Will give it a try tomorrow.

What do you mean? The list of all possible assignees is returned without problems.

**Comment by GrahamCampbell** [comment] 2019-11-04 17:39
> What do you mean? The list of all possible assignees is returned without problems.

Yes, but that's already public information on the GitHub UI, whereas organisation membership is not necessarily public, so making an assignment potentially leaks information.

**Comment by acrobat** [comment] 2019-11-04 20:50
Not much info about this in the api docs, but I found this (it is for repositories). So it could be something like @GrahamCampbell said.

> Typically, we send a 404 error when your client isn't properly authenticated. You might expect to see a 403 Forbidden in these cases. However, since we don't want to provide any information about private repositories, the API returns a 404 error instead.

https://developer.github.com/v3/troubleshooting/#why-am-i-getting-a-404-error-on-a-repository-that-exists

**Comment by OskarStark** [comment] 2019-11-06 17:34
I am the OWNER and CREATOR of the ORG.
I created a personal access token with everything checked, but nothings helps... 😢

**Comment by acrobat** [comment] 2019-11-07 13:10
Hmm that's indeed strange, can you try [contacting github](https://support.github.com/contact) directly? Maybe they can provide more info on the issue, so we are sure it's not an issue on our side!

**Comment by bobeagan** [comment] 2020-04-13 17:33
Super late to the party here but your code example appears that you were trying to pass in the issue ID rather than the issue number. That's likely the cause of your 404

**Comment by OskarStark** [comment] 2020-04-13 17:37
You could be right, would live to have a typed API 🤪 will try again, thanks

**Comment by acrobat** [comment] 2020-04-25 21:56
@OskarStark Do you have an update on this issue? I'm closing this issue for now. If it would be caused by this package, please reopen and leave a comment!

**Closed by acrobat** 2020-04-25 21:56 UTC

**Comment by noplanman** [comment] 2021-04-17 10:23
Just as a comment, I was running into 404 errors too and it turned out to be a permissions problem.

GitHub API really could do with some more helpful error messages...
